version: "3.8"
services:

  app1:
    image: springboot-helloworld
    container_name: app1
    external_links:
      - postrgesql2:postgresql2
    ports:
      - "8080:8080"
    networks:
      - alterra
    volumes:
      - ./volumes:/example
networks:
  alterra:
    external: true